USE casacidada;

CREATE TABLE USUARIO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL UNIQUE,
	SENHA VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(11),
	PERMISSAO INT,
	DATA_NASC DATE,
	DATA_CRIACAO DATE 
);

CREATE TABLE IMOVEL(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CEP VARCHAR(20) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	COMPLEMENTO VARCHAR(50),
	NUM_RESIDENCIA INT NOT NULL,
	NOME_PROPRIETARIO VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
    VALOR_ALUGUEL DOUBLE NOT NULL,
	DATA_INICIO_CONTRATO DATE NOT NULL,
	DATA_TERMINO_CONTRATO DATE NOT NULL,
	STATUS VARCHAR(13),
	DESCRICAO VARCHAR(100)
);

CREATE TABLE RECEBIMENTOS(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DATA_RECEBIMENTO DATE NOT NULL,
	VALOR DOUBLE,
    TIPO_DOACAO VARCHAR(10),
    DESCRICAO VARCHAR(50)
);

CREATE TABLE ASSISTIDO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR (50) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	TELEFONE VARCHAR(20),
	DATA_CADASTRO DATE NOT NULL,
	DATA_NASC DATE NOT NULL,
	ID_IMOVEL INT,
	CONSTRAINT FK_IMOVEL_ASSISTIDO FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEL (ID)
);

CREATE TABLE PARCEIRO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	TIPO VARCHAR (15),
	CNPJ VARCHAR (14),
	AREA_ATUACAO VARCHAR (15),
	TELEFONE VARCHAR (11)
);

CREATE TABLE GASTOS(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_ASSISTIDO INT NOT NULL,
	DATA_GASTO DATE NOT NULL,
	VALOR DOUBLE NOT NULL,
	CONSTRAINT FK_ASSISTIDO_GASTO FOREIGN KEY (ID_ASSISTIDO) REFERENCES ASSISTIDO (ID)
);

CREATE TABLE NOTICIAS(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CADASTRANTE INT NOT NULL,
    TITULO VARCHAR(50),
    DESCRICAO VARCHAR(500),
    DATA_PUBLICACAO DATE,
    CONSTRAINT FK_NOTICIA_USUARIO FOREIGN KEY (ID_CADASTRANTE) REFERENCES USUARIO (ID)
);